### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by chenk2** [matthiaskaiser/jmet#1]
Hi,
when I run the following command
`java -jar jmet-0.1.0-all.jar -Q event -I ActiveMQ -Y xterm localhost 61616`
i'm getting the following output:

```
ERROR d.c.j.JMET [main] Failed to setup external libraries!
java.nio.file.NoSuchFileException: external
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_91]
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_91]
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_91]
    at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[?:1.8.0_91]
    at java.nio.file.Files.newDirectoryStream(Files.java:525) ~[?:1.8.0_91]
    at de.codewhite.jmet.JMET.setupExternalLibs(JMET.java:174) [jmet-0.1.0-all.jar:?]
    at de.codewhite.jmet.JMET.setup(JMET.java:118) [jmet-0.1.0-all.jar:?]
    at de.codewhite.jmet.JMET.main(JMET.java:58) [jmet-0.1.0-all.jar:?]
INFO d.c.j.t.JMSTarget [main] Connected with ID: ID:chen-thinkpad-t440p-41215-1471083151059-0:1
INFO d.c.j.t.JMSTarget [main] Sent gadget "BeanShell1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "CommonsBeanutils1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "CommonsCollections1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "CommonsCollections2" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "CommonsCollections3" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "CommonsCollections4" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "CommonsCollections5" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "Groovy1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "Hibernate1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "Hibernate2" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "Jdk7u21" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "JSON1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "ROME" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "Spring1" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Sent gadget "Spring2" with command: "xterm"
INFO d.c.j.t.JMSTarget [main] Shutting down connection ID:chen-thinkpad-t440p-41215-1471083151059-0:1
```

Any idea what's missing?

**Comment by chenk2** [comment]
Nevermind, I created the directory named "external" and it works :+1:

**Comment by matthiaskaiser** [comment]
Yes, you may create the "external" and "scripts" directory. Great you solved it yourself!
