### ISSUE TITLE
Incorrect Content-Type for RabbitMQ

### ISSUE THREAD

**Issue by GrrrDog** [matthiaskaiser/jmet#3]
Jmet sends a payload to a RabbitMQ server, but sets an incorrect content-type (application/octet-stream). It has to be "application/x-java-serialized-object". However, I've not found a way to set it in code.

**Comment by 0xwindows** [comment]
➜  exp java -jar jmet-0.1.0-all.jar -u guest -pw guest -Q hello.world.queue -I RabbitMQ -Y calc 127.0.0.1 5672
ERROR d.c.j.JMET [main] Failed to setup external libraries!
java.nio.file.NoSuchFileException: external
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_65]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_65]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_65]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407) ~[?:1.8.0_65]
	at java.nio.file.Files.newDirectoryStream(Files.java:525) ~[?:1.8.0_65]
	at de.codewhite.jmet.JMET.setupExternalLibs(JMET.java:174) [jmet-0.1.0-all.jar:?]
	at de.codewhite.jmet.JMET.setup(JMET.java:118) [jmet-0.1.0-all.jar:?]
	at de.codewhite.jmet.JMET.main(JMET.java:58) [jmet-0.1.0-all.jar:?]
ERROR d.c.j.JMET [main] Init failed:
com.rabbitmq.jms.util.RMQJMSException
	at de.codewhite.jmet.target.impl.RabbitMQTarget.init(RabbitMQTarget.java:36) ~[jmet-0.1.0-all.jar:?]
	at de.codewhite.jmet.JMET.pwn(JMET.java:82) [jmet-0.1.0-all.jar:?]
	at de.codewhite.jmet.JMET.main(JMET.java:59) [jmet-0.1.0-all.jar:?]
Caused by: java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:124) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:378) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:813) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:767) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:857) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.jms.admin.RMQConnectionFactory.getRabbitConnection(RMQConnectionFactory.java:96) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.jms.admin.RMQConnectionFactory.createConnection(RMQConnectionFactory.java:87) ~[jmet-0.1.0-all.jar:?]
	at de.codewhite.jmet.target.impl.RabbitMQTarget.init(RabbitMQTarget.java:30) ~[jmet-0.1.0-all.jar:?]
	... 2 more
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:361) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:226) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:378) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:813) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:767) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:857) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.jms.admin.RMQConnectionFactory.getRabbitConnection(RMQConnectionFactory.java:96) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.jms.admin.RMQConnectionFactory.createConnection(RMQConnectionFactory.java:87) ~[jmet-0.1.0-all.jar:?]
	at de.codewhite.jmet.target.impl.RabbitMQTarget.init(RabbitMQTarget.java:30) ~[jmet-0.1.0-all.jar:?]
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290) ~[?:1.8.0_65]
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:139) ~[jmet-0.1.0-all.jar:?]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:542) ~[jmet-0.1.0-all.jar:?]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_65]

**Comment by matthiaskaiser** [comment]
As far as I can see the "application/octet-stream" is set internally in the JMS driver of RabbitMQ.

You could create a subclass of "RMQMessageProducer" and implement your own "sendAMQPMessage(RMQDestination destination, RMQMessage msg, int deliveryMode, int priority, long timeToLive)" method which changes the contentType to what you need.
You might want to create your own  "de.codewhite.jmet.target.impl.RabbitMQTarget" class for that  ;-)
